### ISSUE TITLE
test_member_CLUDS fails during cleanup in Mitaka

### ISSUE THREAD

**Issue by dflanigan** [F5Networks/f5-openstack-lbaasv2-driver#113]
* Title: test_member_CLUDS fails during cleanup in Mitaka
* Labels: Bug
* Milestone: Leave this field empty.
* Assignee: @richbrowne 
* Attachments: 
  * /etc/neutron/server.log [server.log.txt](https://github.com/F5Networks/f5-openstack-lbaasv2-driver/files/285233/server.log.txt)

#### Agent Version
LBaaSv2 version is 8.0.2
agent version is 8.0.2

#### Operating System
CentOS 7

#### OpenStack Release
Mitaka

#### Description
While running the test_CLUDS in mitaka test_member_CLUDS fails during cleanup while trying to delete pools.  This was the fifth test to run. The interesting errors in the server.log file starts at 12:35:33. Have
discussed this problems with @jlongstaf and @zancas 

#### Deployment
Session is still up: flanigan-over-mit-116-0526-01  : This is a overcloud setup in a mitaka version of openstack.  BigIP version 11.6

**Comment by richbrowne** [comment]
I need to see the f5-openstack-agent.log file too.  For some reason the
loadbalancer is still in UPDATE state, which means the previous operation
is not yet completed.

**Comment by richbrowne** [comment]
I looked at this but saw no errors in the f5-openstack-agent.log around the time that this test failed.

**Comment by richbrowne** [comment]
This issue is likely caused by the way in which the polling client is initialized and implemented.  In some cases the .4 second polling interval is too short and causes the api call to happen when the prior one is still in progress.  This results in an exception which is not handled by the polling client.

The call to delete should not be retried.  In fact, the proper way is to test the existence of the object, and if it exists try to delete, then poll for the existence until it is removed.

So the pattern is:

if x.exists()
    x.delete()
while x.exists() and retries < max_retries:
    sleep (interval)

if x.exists():
    return ERROR
