### ISSUE TITLE
install_tlc.sh script mutates the state of the test-runner container via apt update

### ISSUE THREAD

**Issue by zancas** [F5Networks/f5-openstack-lbaasv2-driver#559]
The use of apt update/apt install in the test infrastructure code eliminates the possibility of having a stable (invariant) test runner between test runs.   This code must be rewritten (probably by using a customized docker container to be the test-runner that contains the necessary functionality) ASAP.

**Comment by dflanigan** [comment]
@zancas : we need more details on the problem.

**Comment by pjbreaux** [comment]
I think the gist of this is that the apt-get install/update commands mean that the container running our tests changes each time we build it. This is bad because we'd like to have only the code-under-test and the dependencies it uses changing, leaving all other things stable in that container. We don't want a change to some tertiary package possibly breaking all of our builds. We can create a container that has all the underlying packages installed, then we only do a pip install -e of our code and its dependencies.

**Comment by richbrowne** [comment]
Moved from tlc environment
